import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Icons } from "@/components/Icons";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TYC Africa Trust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={poppins.className}>
        <div className="flex flex-col min-h-screen ">
          <div className="top-0 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
            <div className="border-b flex h-52 items-center justify-between px-[80px] bg-navbar">
              <Link href={"/"}>
                <Image
                  src={"TYC-Logo-Large.svg"}
                  alt={"TYC Africa Logo"}
                  width={160}
                  height={144}
                />
              </Link>
              <div className="flex  min-h-[75] justify-end items-center gap-4 text-navtext text-[25px]">
                <div className="flex items-center gap-3 px-3 border-r">
                  <Link href={"/"}>
                    <p className="hidden md:block"> Search</p>
                  </Link>{" "}
                  <Icons.search />
                </div>
                <div className="flex items-center gap-3 px-3 border-r">
                  <Link href={"/"}>
                    <p className="hidden md:block"> Donate</p>{" "}
                  </Link>{" "}
                  <Icons.donate />
                </div>
                <Navbar />
              </div>
            </div>
          </div>
          <div className="flex-1 w-full ">{children}</div>

          <Footer/>

        </div>

      </body>
    </html>
  );
}
